預測會不會買第二筆
or say, 買第二筆的機率有多大

In [151]:
import os
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
import matplotlib as mpl
%matplotlib inline
#sns.set_style("whitegrid",{"font.sans-serif":['simhei', 'Arial']})

pd.set_option('display.max_columns', 500)
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

In [3]:
df_1st = pd.read_csv('/Users/yichingchan/Documents/91APP/df_1st.csv')
df_1st.head()

,MemberId,Quantity,SalesOrderSlaveTotalPayment,ECouponDiscount,PromotionDiscount,get_OpenCardPresent,get_LastBirthdayPresentYear,location_North,location_South,location_Mid,location_East,Weekend,time_Midnight,time_Morning,time_Afternoon,time_Night,season_spring,season_summer,season_fall,season_winter,TrackSourceTypeDef_AndroidApp,TrackSourceTypeDef_Web,TrackSourceTypeDef_iOSApp,TrackDeviceTypeDef_Mobile,TrackDeviceTypeDef_PC,TrackDeviceTypeDef_Pad,PayProfileTypeDef_ATM,PayProfileTypeDef_CreditCardOnce,PayProfileTypeDef_Family,PayProfileTypeDef_LinePay,PayProfileTypeDef_SevenEleven,DeliverTypeDef_Family,DeliverTypeDef_Home,DeliverTypeDef_SevenEleven,"cut_UnitPrice_(399.0, 3500.0]","cut_UnitPrice_(311.0, 399.0]","cut_UnitPrice_(235.0, 311.0]","cut_UnitPrice_(199.0, 235.0]","cut_UnitPrice_(0.0, 199.0]",count,mean_payment,retain
0,192540,6,1357.0,False,False,False,False,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,4,5,226.166667,True
1,205786,5,1033.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,4,1,206.600000,False
2,297791,1,299.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,299.000000,False
3,403195,1,299.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,299.000000,False
4,808449,6,1194.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,6,2,199.000000,True

In [4]:
df_2nd = pd.read_csv('/Users/yichingchan/Documents/91APP/df_2nd.csv')
df_2nd.head()

,MemberId,Quantity,SalesOrderSlaveTotalPayment,"cut_UnitPrice_(399.0, 3500.0]","cut_UnitPrice_(311.0, 399.0]","cut_UnitPrice_(235.0, 311.0]","cut_UnitPrice_(199.0, 235.0]","cut_UnitPrice_(0.0, 199.0]",ECouponDiscount,PromotionDiscount,get_OpenCardPresent,get_LastBirthdayPresentYear,location_North,location_South,location_Mid,location_East,Weekend,time_Midnight,time_Morning,time_Afternoon,time_Night,season_spring,season_summer,season_fall,season_winter,TrackSourceTypeDef_AndroidApp,TrackSourceTypeDef_Web,TrackSourceTypeDef_iOSApp,TrackDeviceTypeDef_Mobile,TrackDeviceTypeDef_PC,TrackDeviceTypeDef_Pad,PayProfileTypeDef_ATM,PayProfileTypeDef_CreditCardOnce,PayProfileTypeDef_Family,PayProfileTypeDef_LinePay,PayProfileTypeDef_SevenEleven,DeliverTypeDef_Family,DeliverTypeDef_Home,DeliverTypeDef_SevenEleven,count,fre_mean,mean_payment,retain
0,1384,4,1147.0,1,0,1,0,2,False,False,False,False,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,3,195.0,387.833333,True
1,1391,11,2340.0,2,2,1,0,6,True,True,True,False,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,4,734.0,208.020833,True
2,1448,8,2042.0,0,1,7,0,0,False,False,False,False,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,7,9.0,272.666667,True
3,1469,7,1427.0,0,1,2,0,4,False,False,True,True,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,10,11.0,196.208333,True
4,1490,10,2313.0,1,1,3,0,5,True,True,True,True,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0,0,1,3,30.0,231.300000,True

In [163]:
df_3rd = pd.read_csv('/Users/yichingchan/Documents/91APP/df_3rd.csv')
df_3rd.head()

,MemberId,Quantity,SalesOrderSlaveTotalPayment,ECouponDiscount,PromotionDiscount,get_OpenCardPresent,get_LastBirthdayPresentYear,location_North,location_South,location_Mid,location_East,Weekend,time_Midnight,time_Morning,time_Afternoon,time_Night,season_spring,season_summer,season_fall,season_winter,TrackSourceTypeDef_AndroidApp,TrackSourceTypeDef_Web,TrackSourceTypeDef_iOSApp,TrackDeviceTypeDef_Mobile,TrackDeviceTypeDef_PC,TrackDeviceTypeDef_Pad,PayProfileTypeDef_ATM,PayProfileTypeDef_CreditCardOnce,PayProfileTypeDef_Family,PayProfileTypeDef_LinePay,PayProfileTypeDef_SevenEleven,DeliverTypeDef_Family,DeliverTypeDef_Home,DeliverTypeDef_SevenEleven,"cut_UnitPrice_(399.0, 3500.0]","cut_UnitPrice_(311.0, 399.0]","cut_UnitPrice_(235.0, 311.0]","cut_UnitPrice_(199.0, 235.0]","cut_UnitPrice_(0.0, 199.0]",count,mean_payment,retain,fre_mean
0,192540,6,1357.0,False,False,False,False,0,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,1,4,5,227.944444,True,215.0
1,80753,1,253.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,3,204.500000,False,77.5
2,239980,5,1016.0,False,False,False,False,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,4,3,233.733333,False,60.5
3,658726,1,199.0,False,False,False,False,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,6,201.000000,True,0.0
4,658726,1,263.0,False,False,False,False,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,6,201.000000,True,0.0

## ML

In [143]:
from sklearn.metrics import accuracy_score, classification_report, precision_recall_curve, confusion_matrix,roc_auc_score
from sklearn.model_selection import cross_val_score, StratifiedKFold, KFold, GridSearchCV
from sklearn.feature_selection import RFECV, RFE
from sklearn.metrics import roc_curve, auc, recall_score, f1_score, precision_score,average_precision_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [69]:
from sklearn.model_selection import train_test_split

In [154]:
'''def dataset_split(df):
    train_Y = df['retain']
    print(train_Y.value_counts())

    drop_list =['MemberId', 'count', 'retain']
    train_X = df.drop(drop_list ,axis=1)
    column_name = train_X.columns.tolist()

    train_X = train_X.values
    train_X, test_X, train_Y, test_Y = train_test_split(train_X, train_Y, test_size=0.2)
    
    return train_X, test_X, train_Y, test_Y, column_name'''
    

def classification_model(df, model):
    print(datetime.now())
    
    #train test split
    train_Y = df['retain']
    print(train_Y.value_counts())

    drop_list =['MemberId', 'count', 'retain']
    train_X = df.drop(drop_list ,axis=1)
    column_name = train_X.columns.tolist()

    train_X = train_X.values
    train_X, test_X, train_Y, test_Y = train_test_split(train_X, train_Y, test_size=0.2)
    
    #model
    model = model
    model.fit(train_X, train_Y)
    print('model fit')
    
    ##cross validation score
    score = cross_val_score(model, train_X, train_Y, cv=5).mean()
    print("cross validation score: %0.2f (+/- %0.2f)" % (score.mean(), score.std() * 2))
    
    ##predict
    pred_Y = model.predict(test_X)
    probs_Y = model.predict_proba(test_X)
    probs_Y = probs_Y[:, 1] ## keep probabilities for the positive outcome only
    
    ##evaluation
    accy = accuracy_score(test_Y, pred_Y)
    f1 = f1_score(test_Y, pred_Y)
    recall = recall_score(test_Y, pred_Y)
    precision =precision_score(test_Y, pred_Y)
    auc = roc_auc_score(test_Y, probs_Y)
    ap = average_precision_score(test_Y, probs_Y) 
    print('evaluation without RFECV: accy: %0.3f, f1: %0.3f, recall: %0.3f, precision: %0.3f, auc: %0.3f, ap: %0.3f' % (accy, f1, recall, precision, auc, ap))
    
    ##confusion matrix
    labels = np.unique(test_Y)
    conf_m = confusion_matrix(test_Y, pred_Y, labels=labels)
    conf_m = pd.DataFrame(conf_m, index=labels, columns=labels)
    #prctg = conf_m/conf_sum
    print('confusion matrix without RFECV:', conf_m)
    
    #feature importance
    try:
        feature_importances = pd.Series(model.feature_importances_, index=column_name)
    except:
        feature_importances = pd.Series(['None']) 
    
    #rfecv
    '''selector= RFECV(model, step=1, cv=StratifiedKFold(2), scoring='accuracy')
    selector.fit(train_X, train_Y)
    print("Optimal number of features : %d" % selector.n_features_)
    feature_ranking = sorted(zip(selector.ranking_,column_name))
    for i in feature_ranking:
        print(i)
        
    pred_Y_rfe = selector.predict(test_X)
    probs_Y_rfe = selector.predict_proba(test_X)
    probs_Y_rfe = probs_Y_rfe[:, 1] ## keep probabilities for the positive outcome only
        
    ##evaluation
    accy_rfe = accuracy_score(test_Y, pred_Y_rfe)
    #f1_rfe = f1_score(test_Y, pred_Y_rfe)
    recall_rfe = recall_score(test_Y, pred_Y_rfe)
    #precision_rfe =precision_score(test_Y, pred_Y_rfe)
    auc_rfe = roc_auc_score(test_Y, probs_Y_rfe)
    print('evaluation with RFECV: accy: %0.3f, recall: %0.3f, auc: %0.3f' % (accy_rfe, recall_rfe, auc_rfe))
    
    ##confusion matrix
    labels = np.unique(test_Y)
    conf_m_rfe = confusion_matrix(test_Y, pred_Y_rfe, labels=labels)
    conf_m_rfe = pd.DataFrame(conf_m_rfe, index=labels, columns=labels)
    #prctg_rfe = conf_m_rfe/conf_sum_rfe
    print('confusion matrix with RFECV:', conf_m_rfe)'''
    print(datetime.now())
    
    return pred_Y, probs_Y, feature_importances, accy, f1, recall, precision, auc, conf_m, ap

In [165]:
df_lst = [df_1st, df_2nd, df_3rd]
model_lst = [LogisticRegression(), RandomForestClassifier(), XGBClassifier()]

accy_lst = []
f1_lst = []
recall_lst = []
precision_lst = []
auc_lst = []
#conf_m_lst = []
feature_lst = []
ap_lst = []

for df in df_lst:
    for model in model_lst:
        pred_Y, probs_Y, feature_importances, accy, f1, recall, precision, auc, conf_m, ap = classification_model(df, model)
        accy_lst.append(accy)
        f1_lst.append(f1)
        recall_lst.append(recall)
        precision_lst.append(precision)
        auc_lst.append(auc)
        ap_lst.append(ap)
        #conf_m_lst.append(conf_m)
        feature_lst.append(feature_importances.to_dict())

2019-06-13 01:22:23.946388
False    288520
True     203310
Name: retain, dtype: int64
model fit
cross validation score: 0.65 (+/- 0.00)
evaluation without RFECV: accy: 0.647, f1: 0.491, recall: 0.411, precision: 0.608, auc: 0.648, ap: 0.563
confusion matrix without RFECV:        False  True
False  46911  10775
True   23953  16727
2019-06-13 01:22:49.562121
2019-06-13 01:22:49.700490
False    288520
True     203310
Name: retain, dtype: int64
model fit
cross validation score: 0.60 (+/- 0.00)
evaluation without RFECV: accy: 0.596, f1: 0.444, recall: 0.391, precision: 0.515, auc: 0.594, ap: 0.493
confusion matrix without RFECV:        False  True
False  42757  14948
True   24779  15882
2019-06-13 01:23:57.133200
2019-06-13 01:23:57.283579
False    288520
True     203310
Name: retain, dtype: int64
model fit
cross validation score: 0.65 (+/- 0.00)
evaluation without RFECV: accy: 0.652, f1: 0.501, recall: 0.425, precision: 0.609, auc: 0.660, ap: 0.574
confusion matrix without RFECV:        False  True
False  47001  11018
True   23196  17151
2019-06-13 01:33:12.808075
2019-06-13 01:33:12.951946
True     109429
False     93881
Name: retain, dtype: int64
model fit
cross validation score: 0.61 (+/- 0.00)
evaluation without RFECV: accy: 0.611, f1: 0.672, recall: 0.744, precision: 0.613, auc: 0.654, ap: 0.672
confusion matrix without RFECV:        False  True
False   8616  10241
True    5573  16232
2019-06-13 01:33:29.479056
2019-06-13 01:33:29.540386
True     109429
False     93881
Name: retain, dtype: int64
model fit
cross validation score: 0.58 (+/- 0.00)
evaluation without RFECV: accy: 0.574, f1: 0.584, recall: 0.553, precision: 0.619, auc: 0.602, ap: 0.615
confusion matrix without RFECV:        False  True
False  11210   7490
True    9818  12144
2019-06-13 01:33:53.220664
2019-06-13 01:33:53.280300
True     109429
False     93881
Name: retain, dtype: int64
model fit
cross validation score: 0.62 (+/- 0.00)
evaluation without RFECV: accy: 0.619, f1: 0.673, recall: 0.728, precision: 0.625, auc: 0.664, ap: 0.681
confusion matrix without RFECV:        False  True
False   9262   9537
True    5949  15914
2019-06-13 01:37:39.530459
2019-06-13 01:37:39.594827
True     199215
False    129072
Name: retain, dtype: int64
model fit
cross validation score: 0.65 (+/- 0.00)
evaluation without RFECV: accy: 0.654, f1: 0.751, recall: 0.858, precision: 0.668, auc: 0.673, ap: 0.743
confusion matrix without RFECV:        False  True
False   8703  17044
True    5661  34250
2019-06-13 01:38:01.161018
2019-06-13 01:38:01.290738
True     199215
False    129072
Name: retain, dtype: int64
model fit
cross validation score: 0.62 (+/- 0.00)
evaluation without RFECV: accy: 0.620, f1: 0.688, recall: 0.692, precision: 0.683, auc: 0.640, ap: 0.703
confusion matrix without RFECV:        False  True
False  13211  12748
True   12226  27473
2019-06-13 01:38:43.979878
2019-06-13 01:38:44.092921
True     199215
False    129072
Name: retain, dtype: int64
model fit
cross validation score: 0.66 (+/- 0.00)
evaluation without RFECV: accy: 0.655, f1: 0.749, recall: 0.849, precision: 0.669, auc: 0.680, ap: 0.748
confusion matrix without RFECV:        False  True
False   9266  16664
True    5988  33740
2019-06-13 01:45:08.783873

In [168]:
eva = pd.DataFrame()
eva['accy'] = accy_lst
eva['f1'] = f1_lst
eva['recall'] = recall_lst
eva['precision'] = precision_lst
eva['auc'] = auc_lst
eva['ap'] = ap_lst

eva.index = ['LR1', 'RF1', 'XGB1', 'LR2', 'RF2', 'XGB2', 'LR3', 'RF3', 'XGB3']

In [171]:
LR = eva.transpose()[['LR1', 'LR2', 'LR3']]
RF = eva.transpose()[['RF1', 'RF2', 'RF3']]
XGB = eva.transpose()[['XGB1', 'XGB2', 'XGB3']]

In [175]:
allmod = pd.concat([LR, RF, XGB], axis=1)
allmod.transpose()

          accy        f1    recall  precision       auc        ap
LR1   0.646951  0.490657  0.411185   0.608210  0.648297  0.563243
LR2   0.611087  0.672439  0.744416   0.613153  0.654468  0.671745
LR3   0.654193  0.751055  0.858159   0.667719  0.672976  0.742963
RF1   0.596131  0.444308  0.390595   0.515148  0.594500  0.492897
RF2   0.574345  0.583902  0.552955   0.618519  0.602365  0.615431
RF3   0.619635  0.687513  0.692033   0.683051  0.640485  0.702736
XGB1  0.652177  0.500642  0.425087   0.608861  0.659533  0.574230
XGB2  0.619153  0.672697  0.727896   0.625280  0.663552  0.680790
XGB3  0.655000  0.748680  0.849275   0.669391  0.679636  0.747984

In [177]:
featureRank = pd.DataFrame(feature_lst)
featureRank.index = ['LR1', 'RF1', 'XGB1', 'LR2', 'RF2', 'XGB2', 'LR3', 'RF3', 'XGB3']

In [211]:
print('top 10 feature of RF model:')
print()
print(featureRank.transpose()[['RF1', 'RF2','RF3']].sum(axis=1).sort_values(ascending = False).head(10))

top 10 feature of RF model:

mean_payment                     0.496808
SalesOrderSlaveTotalPayment      0.475742
fre_mean                         0.372389
cut_UnitPrice_(0.0, 199.0]       0.175494
Quantity                         0.167656
cut_UnitPrice_(235.0, 311.0]     0.131314
cut_UnitPrice_(311.0, 399.0]     0.117232
Weekend                          0.078213
get_OpenCardPresent              0.074562
cut_UnitPrice_(399.0, 3500.0]    0.065950
dtype: float64

In [212]:
print('top 10 feature of XGB model:')
print()
print(featureRank.transpose()[['XGB1', 'XGB2','XGB3']].sum(axis=1).sort_values(ascending = False).head(10))

top 10 feature of XGB model:

get_OpenCardPresent             0.743739
get_LastBirthdayPresentYear     0.535093
fre_mean                        0.419343
TrackSourceTypeDef_iOSApp       0.165126
ECouponDiscount                 0.134624
TrackSourceTypeDef_Web          0.101586
PromotionDiscount               0.089481
season_winter                   0.076165
cut_UnitPrice_(235.0, 311.0]    0.071319
season_spring                   0.065387
dtype: float64

In [192]:
featureRank.transpose()['XGB2'].sort_values(ascending = False).head(10)

get_LastBirthdayPresentYear      0.277397
fre_mean                         0.154296
get_OpenCardPresent              0.121199
TrackSourceTypeDef_iOSApp       0.0634108
TrackSourceTypeDef_Web          0.0443008
ECouponDiscount                 0.0428451
season_winter                   0.0331905
PromotionDiscount               0.0275319
cut_UnitPrice_(235.0, 311.0]    0.0254126
season_spring                   0.0231613
Name: XGB2, dtype: object

In [191]:
featureRank.transpose()['XGB1'].sort_values(ascending = False).head(10)

get_OpenCardPresent              0.555322
get_LastBirthdayPresentYear     0.0746277
ECouponDiscount                 0.0673218
TrackSourceTypeDef_iOSApp       0.0517828
TrackDeviceTypeDef_Mobile       0.0202931
season_winter                   0.0185183
PromotionDiscount               0.0183939
cut_UnitPrice_(235.0, 311.0]    0.0164182
DeliverTypeDef_Home             0.0144987
TrackSourceTypeDef_Web          0.0131449
Name: XGB1, dtype: object

In [137]:
featureRank.transpose()

,0,Quantity,SalesOrderSlaveTotalPayment,ECouponDiscount,PromotionDiscount,get_OpenCardPresent,get_LastBirthdayPresentYear,location_North,location_South,location_Mid,location_East,Weekend,time_Midnight,time_Morning,time_Afternoon,time_Night,season_spring,season_summer,season_fall,season_winter,TrackSourceTypeDef_AndroidApp,TrackSourceTypeDef_Web,TrackSourceTypeDef_iOSApp,TrackDeviceTypeDef_Mobile,TrackDeviceTypeDef_PC,TrackDeviceTypeDef_Pad,PayProfileTypeDef_ATM,PayProfileTypeDef_CreditCardOnce,PayProfileTypeDef_Family,PayProfileTypeDef_LinePay,PayProfileTypeDef_SevenEleven,DeliverTypeDef_Family,DeliverTypeDef_Home,DeliverTypeDef_SevenEleven,"cut_UnitPrice_(399.0, 3500.0]","cut_UnitPrice_(311.0, 399.0]","cut_UnitPrice_(235.0, 311.0]","cut_UnitPrice_(199.0, 235.0]","cut_UnitPrice_(0.0, 199.0]",mean_payment,fre_mean
LR1,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RF1,NaN,0.048668,0.209138,0.014818,0.013391,0.033578,0.039143,0.019469,0.016134,0.017492,0.007577,0.034748,0.013228,0.015762,0.018161,0.020686,0.014099,0.013265,0.014268,0.011017,0.005419,0.006411,0.005476,0.006449,0.006680,0.000022,0.000232,0.001911,0.003332,0.000159,0.003035,0.003316,0.002030,0.003052,0.019901,0.035108,0.040737,0.017046,0.054820,0.210223,NaN
XGB1,NaN,0.009266,0.009997,0.062580,0.018840,0.573268,0.070511,0.004044,0.007088,0.000000,0.000000,0.008522,0.004631,0.000000,0.000000,0.003476,0.009021,0.010562,0.008340,0.015352,0.004789,0.014676,0.055656,0.006661,0.008588,0.000000,0.001969,0.009664,0.001257,0.009074,0.014489,0.000000,0.013868,0.000000,0.005809,0.006766,0.015687,0.007979,0.002076,0.005493,NaN
LR2,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RF2,NaN,0.066430,0.128290,0.010976,0.013863,0.016407,0.018446,0.016947,0.014134,0.014078,0.006060,0.019311,0.011232,0.012946,0.015095,0.016853,0.011432,0.011510,0.012170,0.008717,0.004686,0.005150,0.004517,0.007012,0.006960,0.000014,0.000271,0.003456,0.006505,0.000151,0.006438,0.006532,0.003756,0.006672,0.029622,0.046966,0.055868,0.021155,0.068424,0.129804,0.161146
XGB2,NaN,0.010088,0.008458,0.054595,0.027978,0.132337,0.238458,0.010084,0.005818,0.002959,0.002494,0.000000,0.000000,0.004790,0.000000,0.000000,0.023076,0.026840,0.000000,0.037074,0.000000,0.041245,0.076359,0.000000,0.011630,0.000000,0.007907,0.006688,0.000000,0.013647,0.017760,0.000000,0.021110,0.000000,0.011173,0.005747,0.024589,0.014384,0.003597,0.006301,0.152816